export const ENDPOINT = {
  GET_CUSTOMERS: '/customers',
  UPDATE_CUSTOMERS: '/customer'
};

export const ACTION_TYPES = {
  FETCH_CUSTOMERS_REQUEST: 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_FAILED: 'FETCH_CUSTOMERS_FAILED',
  FETCH_CUSTOMERS_SUCCEEDED: 'FETCH_CUSTOMERS_SUCCEEDED',

  UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_FAILED: 'UPDATE_CUSTOMER_FAILED',
  UPDATE_CUSTOMER_SUCCEEDED: 'UPDATE_CUSTOMER_SUCCEEDED',
  UPDATE_CUSTOMER_RESET: 'UPDATE_CUSTOMER_RESET'
};
